language:
- node_js
node_js:
- 9.2.1
branches:
  only:
  - master
  - develop
services:
- mongodb
before_script:
- npm install
script:
- npm run test
- sonar-scanner -Dsonar.projectKey=jazh-70213154 -Dsonar.organization=jesusz27-github
  -Dsonar.sources=. -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=a23f5b9cdbfa0a3cfeb017613a0a16c9b32b0bf5
deploy:
  provider: heroku
  api_key:
    secure: QVP7ViprqRVghfdXGSHumziQrCnb4th+WrbHWFCvrIN3BLizfUv2nfkeh5qSSzeAmYqqjhSSJTHg4urEL2DyAmI4VkVjYgPfcgr2Hckb6EdG1f69sieBrhe+pY85duYxiqen2iq9vA3hscjGs/pU/A1lks6q9hP3W2Buc2Y/cqEmqMId/hyfAHQgKSEOzBJ2/6N1FiMGqQdYfybSbFd0kk4tD+3X0Vn3oRqzzMAwLs1OnPN6htUQ4yXvU4UBn7fJ1602kLF1vElElAgbgHfnKe6ueSF3TwAu1KOP1BfJBLNLEHDpYEg2raZY+yxOQvk0Ce0aExMpNBcemgDyIPd9TWOSSGLb690ovmbFVwlwTyB0USFtCWZH2O/qPIM5U+8oTAX2mCf8Jk+KyuW8KQG3yh7GISs0NfS7WfJorGMGR+eMvhEOhAs+ZfrH7kOHxrbAvbCIP9pd7cd36mstp0uGH3gByrIdfwQW0CpCITYgD9vHMfuF7vYd7jWBhTTTdbGEhBtn0q6jCvbwSKuU6h8N9EAaTp/iueyyPQfhhGdBNU2cQghVeBsP62xHtvRSFVXOkRdW7xny5/8quRLHCUxZgJgzOGS2rhi1NCXrVk5Fh07J8A7nQGvwARGnn1pTaa3IUXT0Jj6h9xlIJO31gMJqk91npGkpdzW1dEuXQYgFaQk=
  app: zea-pfm
  on:
    repo: jesusz27/backend-node
    branch: develop
