import express from "express";
const expressListRoutes = require("express-list-routes");
import userRoutes from "./user/user.route";
import contactRoutes from "./contact/contact.route";
import trackRoutes from "./track/track.route";
import trackDetailRoutes from "./track-detail/trackDetail.route";
import authRoutes from "./auth/auth.route";
import personRoutes from "./person/person.route";
const api = express.Router();

api.use("/users", userRoutes);
api.use("/contacts", contactRoutes);
api.use("/tracks", trackRoutes);
api.use("/trackDetails", trackDetailRoutes);
api.use("/auth", authRoutes);
api.use("/persons", personRoutes);
expressListRoutes({ prefix: "/users" }, "users:", userRoutes);
expressListRoutes({ prefix: "/contacts" }, "contact:", contactRoutes);
expressListRoutes({ prefix: "/tracks" }, "track:", trackRoutes);
expressListRoutes({ prefix: "/trackDetails" }, "trackDetail:", trackDetailRoutes);
expressListRoutes({ prefix: "/auth" }, "auth:", authRoutes);
expressListRoutes({ prefix: "/persons" }, "person:", personRoutes);
export default api;