# Users
users:
- &user0 
    _id: {$oid: "161d87b8b260cf35147998ca"}
    idUser: Jesusz27 
    email: jez@a.com
    password: 1234a
    avatar: uploads/default.png
- &user1
    _id: {$oid: "261d87b8b260cf35147998ca"}
    idUser: Jesus1352 
    email: je12@a.com
    password: 1234a
    avatar: uploads/default.png
- &user2
    _id: {$oid: "361d87b8b260cf35147998ca"}
    idUser: Smith
    email: smith@gmail.com
    password: 1234
    avatar: uploads/default.png

# Contacts
contacts:
- &contact0
    _id: {$oid: "5b49ba1ff3dc292dc0f86437"}
    codUser: {$oid: "161d87b8b260cf35147998ca"}
    codContact: {$oid: "261d87b8b260cf35147998ca"}
    status: 'SELECTED'
- &contact1
    codUser: {$oid: "261d87b8b260cf35147998ca"}
    codContact: {$oid: "161d87b8b260cf35147998ca"}

# Tracks
tracks:
- &track0
    _id: {$oid: "5b49ba1ff5dc292dc0f86447"}
    codUser: {$oid: "161d87b8b260cf35147998ca"}
    codContact: {$oid: "261d87b8b260cf35147998ca"}
    trackDetail: {$oid: "5b49ba1ff3cd192dc0f86437"}

# TrackDetails
trackdetails:
- &trackdetail0
    _id: {$oid: "5b49ba1ff3cd192dc0f86437"} 
    idTrack: 'ASWDSDS4S45A4SW4S5W4'
    locationStorage: [{"accuracy":14.777999877929688,"altitude":672,"latitude":40.3884429,"longitude":-3.7227033,"idUser":"Jesusz27","idTrack":"AbCc4a77FabA9Da2BbC2"},{"accuracy":17.893999099731445,"altitude":672,"latitude":40.3884429,"longitude":-3.7227033,"idUser":"Jesusz27","idTrack":"AbCc4a77FabA9Da2BbC2"},{"accuracy":17.893999099731445,"altitude":672,"latitude":40.3884429,"longitude":-3.7227033,"idUser":"Jesusz27","idTrack":"AbCc4a77FabA9Da2BbC2"},{"accuracy":20.441999435424805,"altitude":672,"latitude":40.3884489,"longitude":-3.7227106,"idUser":"Jesusz27","idTrack":"AbCc4a77FabA9Da2BbC2"}]

